# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9745016fc09012f2f36c8eb08cac075759425b7392ebff159fdfbf75a738d814c08458d0df4dc479f9f5ee6cbe9d34a1bc6a1ce247214385b72df57477f2c110

test:
  secret_key_base: 227e90a7b7f12edd527fa94a9b9d02e78363c7fea930b21695206f5d0a3a3cfb834adeabec259b6e68e2a070206820a613549a91e7d3f2e40ddf4bbd4c977574

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
